CREATE BIGFILE TABLESPACE bigtbs_01
DATAFILE 'bigtbs_f1.dat'
SIZE 10M AUTOEXTEND ON;

CREATE UNDO TABLESPACE undotbs_01
DATAFILE 'bigtbs_f1.dat'
SIZE 10M AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE temp_demo
TEMPFILE 'temp01.dbf'
SIZE 5M AUTOEXTEND ON;

CREATE TABLESPACE tbs_01
DATAFILE 'tbs_f2.dat' SIZE 40M
ONLINE;

SELECT * FROM DBA_TABLESPACES;
SELECT * FROM DBA_DATA_FILES;