--CLASS 12/03/2018
CREATE BIGFILE TABLESPACE bigtbs_01
DATAFILE 'bigtbs_f1.dat'
SIZE 10M AUTOEXTEND ON;

CREATE UNDO TABLESPACE undotbs_01
DATAFILE 'bigtbs_f1.dat'
SIZE 10M AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE temp_demo
TEMPFILE 'temp01.dbf'
SIZE 5M AUTOEXTEND ON;

CREATE TABLESPACE tbs_01
DATAFILE 'tbs_f2.dat' SIZE 40M
ONLINE;

DROP TABLESPACE bigtbs_01 INCLUDING CONTENTS AND DATAFILES;
ALTER TABLESPACE TBS_01 OFFLINE;
ALTER TABLESPACE TBS_01 ONLINE;

SELECT * FROM DBA_TABLESPACES;
SELECT STATUS, TABLESPACE_NAME FROM DBA_TABLESPACES;
SELECT * FROM DBA_DATA_FILES;

--USUARIOS, ROLES, PRIVILEGIOS, RECURSOS.
--UN PERFIL PUEDE TENER MUCHOS RECURSOS. THIS IS THE CONTROL ON HARDWARE AND TIME ON A SESSION
--UN USUARIO PUEDE TENER MUCHOS PRIVILEGIOS.
--PRIVILEGE OF CREATIONG TABLESPACE, VIEWS AND OTHERS. (MAINLY COMMANDS)
--RIGHT TO RUN A PL/SQL PACKAGE, AND SO ON.
--PROFILE SET OF LIMITS (RESOURCES) PHYSICAL OR DATABASE.
--RESOURCE RESTRICTION ON HOW USER BEHAVES DURING THE SESSIONS.

--CREATION USERS IN ORACLE
CREATE USER nombre
IDENTIFIED BY password
[DEFAULT TABLESPACE tablespaceName]
[TEMPORARY TABLESPACE nametablespace]
[QUOTA INT {K|M} | UNLIMITED ON tablespaename]
[PROFILE profilename]
[PASSWORD EXPIRE]
[ACCOUNT {LOCK | UNLOCK}];

CREATE USER JVASQUEZ
IDENTIFIED BY 12345678
DEFAULT TABLESPACE TBS_01
QUOTA 10M ON TBS_01;

DROP USER JVASQUEZ [CASCADE]

SELECT * FROM DBA_USERS WHERE USERNAME LIKE '%JVASQUEZ%';
SELECT * FROM DBA_USERS;
UPDATE DBA_USERS SET ACCOUNT_STATUS = 1 WHERE USERNAME = 'SYS'

--PRIVILEGES ON OBJECTS
GRANT SELECT ON username.NameTable TO username;

--SYSTEM PRIVILEGES
GRANT CREATE SESSION, CREATE TABLE TO username;
GRANT CREATE PROCEDURE, EXECUTE ANY PROCEDURE TO username;

--CREATE ROLE
CREATE ROLE miRole;
DROP ROLE miRole;

--CREATE PROFLE
CREATE PROFILE Prof_User_Final LIMIT

--CLASS 14/03/2018
SELECT * FROM DBA_USERS

--DIFERENCE BETWEEN CONNECT AND CREATE
--CONNECT IS A ROL INTRODUCTED IN ORACLE 7
--CREATE IS A PRIVILEGE.

CREATE TABLESPACE THE_BEST_TEACHER
DATAFILE 'julian_vasquez.dbf' SIZE 50M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO
ONLINE;

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER DBA_JULIAN
IDENTIFIED BY DBA_JULIAN
DEFAULT TABLESPACE THE_BEST_TEACHER
QUOTA UNLIMITED ON THE_BEST_TEACHER;

GRANT DBA, CONNECT TO DBA_JULIAN;

CREATE TABLE AGENCIES (
    country VARCHAR2(255),
    resort_name VARCHAR2(255),
    number_of_days INTEGER,
    travel_method VARCHAR2(255),
    price DECIMAL(10,2),
    date_of_issue DATE,
    month VARCHAR(255),
    holiday_id VARCHAR(255)
    )
    
SELECT * FROM AGENCIES   

